#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"

rm -rf "$OPENSHIFT_REPO_DIR/client/static/assets/"

#  On slave/serving gears, need to do the install as part of deploy
#  so check if its needed. Just ensure the custom Node[.js] version is
#  installed.
ensure_node_is_installed

source ${OPENSHIFT_DATA_DIR}/.myenv

echo "export XDG_DATA_HOME=$XDG_DATA_HOME"
echo "export XDG_CONFIG_HOME=$XDG_CONFIG_HOME"
echo "export XDG_CACHE_HOME=$XDG_CACHE_HOME"

