#!/bin/bash

. setenv

set CWD = `pwd`
cd $OPENSHIFT_REPO_DIR

hash bower
#if hash bower 2>/dev/null; then
if [ $? -ne 0 ]; then
  echo "Install bower:"
  npm install -g bower
fi

bower update

cd $CWD

